ITEMS_PER_PAGE = 6

MAX_INGREDIENT_NAME_LENGTH = 200
MAX_INGREDIENT_MEASUREMENT_UNIT_LENGTH = 200
MAX_TAG_NAME_LENGTH = 200
MAX_TAG_COLOR_LENGTH = 7
MAX_TAG_SLUG_LENGTH = 200
MAX_RECIPE_NAME_LENGTH = 200
MIN_COOKING_TIME_IN_MINUTES = 1
MIN_INGREDIENTS_AMOUNT = 1

FORBIDDEN_USERNAMES = ['me']
MAX_NAME_LENGTH = 150
